description: setup docker for desktop
env: osx
steps:
- file: ./scripts/dockerinstall.osx.sh
  description: This will install docker on your machine
  runner: shell
  title: Install docker
- content: |
    # if docker-compose exist, print message and exit 0
    if command -v docker-compose &> /dev/null
    then
        echo "docker-compose is already installed"
        exit 0
    fi

    # Install Docker Compose
    sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose

    # Check Docker Compose version
    docker-compose version
  description: This will install docker-compose on your machine
  runner: shell
  title: Install docker-compose
