description: setup Kubernetes for desktop
env: osx
depends:
  - brew.setup  
steps:
  - content: "\n# Kubernetes is awesome\n## cheers\n### all good\n               \
      \     "
    description: ''
    runner: markdown
    title: Instructions

  - content: 'curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/arm64/kubectl"
      chmod +x ./kubectl
      sudo mv ./kubectl /usr/local/bin/kubectl
      sudo chown root: /usr/local/bin/kubectl
      kubectl version --client'
    description: This will install kubectl on your machine
    runner: shell
    title: Install kubectl
  - content: brew install kubectx
    description: ''
    runner: shell
    title: Install kubectx
  - content: brew install minikube
    description: ''
    runner: shell
    title: Install Minikube
title: Setup Kubernetes
