name: publish-packages

on:
  push:
    branches:
      - master

jobs:
  update-website-docs:
    concurrency: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cocmd
        run: |
          bash -c "$(curl -fsSL https://cocmd.org/linux/install.sh)"
      


  publish-packages:
    concurrency: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: "Install python dependencies"
        run: "pip install pyyaml"
      - name: "Publish packages"
        run: "python .github/scripts/publish_packages.py"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH: "true"